services:
  - type: web
    name: google-maps-scraper
    env: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt && playwright install chromium && playwright install-deps"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
